# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=1.21.11

# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.21.11]

# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.11.45

# The loader version range can only use the major version of FML as bounds
loader_version_range=[1,)

# Mod Properties
mod_version = 1.4.1
mod_group_id=caeruleusTait
mod_id=world_preview
mod_name=World Preview
mod_license=Apache-2.0
mod_archives_base_name=world_preview

# Java version
java_version=21
