# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Minecraft
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# Fabric properties (check these on https://fabricmc.net/develop)
loader_version=0.16.14
fabric_version=0.116.17+1.21.1

# NeoForge properties (https://projects.neoforged.net/neoforged/neoforge)
neo_version=21.1.251
loader_version_range=[1,)

# Mod Properties
mod_version = 1.5.4
maven_group=caeruleusTait
mod_group_id=caeruleusTait
archives_base_name=world_preview
mod_archives_base_name=world_preview
mod_id=world_preview
mod_name=World Preview
mod_license=Apache-2.0

# Java version
java_version=21

# Dependencies
owo_version=0.11.0+1.20
