# Gradle standard
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true

archives_base_name=world_preview
fabric_version=0.141.4+1.21.11
java_version=21
loader_version=0.19.3
loader_version_range=[1,)
maven_group=caeruleusTait
minecraft_version=1.21.11
minecraft_version_range=[1.21.11]
mod_archives_base_name=world_preview
mod_group_id=caeruleusTait
mod_id=world_preview
mod_license=Apache-2.0
mod_name=World Preview
mod_version=1.5.4
neo_version=21.11.45
owo_version=0.11.0+1.20
