pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'world-preview-26.1.2-ml'

include 'fabric'
include 'neoforge'
