modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://modrinth.com/mod/world-preview-fork"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "Caeruleus Draconis, Taiterio"
description = '''
Allows you to preview a map in the new world screen.
'''
logoFile = "assets/world_preview/icon.png"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
    config = "world_preview.mixins.json"
